server:
  port: 9090
spring:
  datasource:
    name: ServiceB
eureka:
  instance:
    namespace: localhost
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka